version: "3"
services:
  web:
    build:
      context: ./nginx
    image: asatrya/limesurvey-nginx
    ports:
      - "8181:80"
    restart: always
    depends_on:
      - php
      - mysqldb
    volumes:
      - public:/var/www/html/

  php:
    build:
      context: ./php
    image: asatrya/limesurvey-php
    restart: always
    volumes:
      - public:/var/www/html/public/

  mysqldb:
    build: 
      context: ./mysql
    image: asatrya/limesurvey-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "8989:3306"
    volumes:
      - vol_mysql_data:/var/lib/mysql

volumes: 
  public:
  vol_mysql_data: