version: "3"
services:
  web:
    build:
      context: ./nginx
    image: asatrya/limesurvey-nginx
    ports:
      - "8181:80"
    restart: always
    depends_on:
      - php
      - mysqldb
    volumes:
      - vol_php_public:/var/www/html/
      - vol_php_tmp:/var/www/html/tmp/

  php:
    build:
      context: ./php
    image: asatrya/limesurvey-php
    restart: always
    env_file:
      - .env
    volumes:
      - vol_php_public:/var/www/html/public/
      - vol_php_tmp:/var/www/html/public/tmp/

  mysqldb:
    build: 
      context: ./mysql
    image: asatrya/limesurvey-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "8989:3306"
    volumes:
      - vol_mysql_data:/var/lib/mysql

volumes: 
  vol_php_public:
    # uncomment lines below to mount host volume (suitable for local development)
    # driver: local
    # driver_opts:
    #   type: none
    #   device: $PWD/php/public
    #   o: bind
  vol_php_tmp:
  vol_mysql_data:
